### ISSUE TITLE
Every app builded for Android crashes after updating to Unity 2018.3.0f2

### ISSUE THREAD

**Issue by jsancheztheia** [artoolkit/arunity5#205]
Hello,

I'm experiencing a problem running an app built on Unity 2018.3.0f2, using the latest Artoolkit plugin available here. The app's built on Unity 2018.2.15f1 and apparently works properly, but it's not possible to avoid updating Unity for much more time.

The app build correctly, but crashes immediatly after it's opened. Android Studio shows this log on the crash:

```
01-10 16:17:32.249 19752-19752/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ar.theia.demogps, PID: 19752
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{ar.example.project/org.artoolkit.ar.unity.UnityARPlayerActivity}: java.lang.ClassNotFoundException: Didn't find class "org.artoolkit.ar.unity.UnityARPlayerActivity" on path: DexPathList[[zip file "/data/app/ar.example.project-2/base.apk"],nativeLibraryDirectories=[/data/app/ar.example.project-2/lib/arm, /data/app/ar.example.project-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2328)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
        at android.app.ActivityThread.access$900(ActivityThread.java:150)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.artoolkit.ar.unity.UnityARPlayerActivity" on path: DexPathList[[zip file "/data/app/ar.example.project-2/base.apk"],nativeLibraryDirectories=[/data/app/ar.example.project-2/lib/arm, /data/app/ar.example.project-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477) 
        at android.app.ActivityThread.access$900(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5418) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.NoClassDefFoundError: org.artoolkit.ar.unity.UnityARPlayerActivity
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:338)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        		... 13 more
    	Suppressed: java.lang.ClassNotFoundException: org.artoolkit.ar.unity.UnityARPlayerActivity
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 12 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

Any idea for solving this problem?

Thanks.

**Comment by MatthewHallberg** [comment]
I actually just had this problem and when I built the unity package on my mac it was missing one of the Android plugins causing that crash. If you load up the arunityX_Android_Player project in Android Studio and rebuild the arunitXPlayer project it will generate a release.aar file which needs to go into the Plugins folder and then it should work. Also I did use the above mentioned artoolkitx project, not this one.
