### ISSUE TITLE
Nvidia Shield (Android 5.1.1 Unity 5.2.2f1) couldn't find "libcurl.so"

### ISSUE THREAD

**Issue by MaxMalliaParfitt** [artoolkit/arunity5#32]
Hi,
Loving the toolkit, with great success until just now on the Nvidia Shield tablet.
This works on multiple android phones and is on the Play Store - just crashing on this device - how many more might be affected?
Is this something i have missed or done wrong?

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.2.2f1
Device model      : NVIDIA SHIELD Tablet
Device fingerprint: nvidia/wx_na_wf/shieldtablet:5.1.1/LMY48C/36442_589.1541:user/release-keys
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.COINSFULCRO.BrooklynStudio-1/base.apk"],nativeLibraryDirectories=[/data/app/com.COINSFULCRO.BrooklynStudio-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libcurl.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:988)
	at org.artoolkit.ar.base.NativeInterface.loadNativeLibrary(NativeInterface.java:74)
	at org.artoolkit.ar.unity.CameraSurface.<clinit>(CameraSurface.java:70)
	at org.artoolkit.ar.unity.UnityARPlayerActivity.onResume(UnityARPlayerActivity.java:153)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
	at android.app.Activity.performResume(Activity.java:6076)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2985)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3027)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
	at android.app.ActivityThread.access$800(ActivityThread.java:152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5273)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Looking forward to your reply :-)
Regards
Max

**Comment by 66point99** [comment]
I can confirm that this issue also occurs on:
Nexus 4 / 4.4.4
Dell Venue 7840 / 5.1
Nexus 5 / 6.0

**Comment by wallywyyoung** [comment]
This is a known bug. ARWrapper changed from using libCurl, libCrypto, and libSSL as shared objects to using a static linkage. I believe there was an issue with the build of libARWrapper. Placing the 3 dependent shared objects (libCurl, libCrypto, libSSL) from a previous release of ARToolKit for Unity works as a work-around (for now).

**Comment by MaxMalliaParfitt** [comment]
Hi Wally,

 

This worked a charm, many thanks.

Sorry for the slow response – lots of things after Autodesk University to bottom out.

 

Regards

 

Max

**Comment by wallywyyoung** [comment]
Happy to help! =)
