### ISSUE TITLE
Plugin crashes app on certain Android devices (Couldn't find libcurl.so)

### ISSUE THREAD

**Issue by Jickelsen** [artoolkit/arunity5#36]
I have tested this library on a number of Android Devices, but the Unity app always seems to crash at startup on LG Galaxy Nexus 5 devices. Here's some of the logcat output. Seems to do with libcurl.

```
I/NativeInterface( 3531): Attempting to load library: ARWrapper
D/AndroidRuntime( 3531): Shutting down VM
E/AndroidRuntime( 3531): FATAL EXCEPTION: main
E/AndroidRuntime( 3531): Process: se.tii3, PID: 3531
E/AndroidRuntime( 3531): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime( 3531): Unity version     : 5.2.3f1
E/AndroidRuntime( 3531): Device model      : LGE Nexus 5
E/AndroidRuntime( 3531): Device fingerprint: google/hammerhead/hammerhead:5.1.1/LMY48I/2074855:user/release-keys
E/AndroidRuntime( 3531):
E/AndroidRuntime( 3531): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/se.tii3-1/base.apk"],nativeLibraryDirectories=[/data/app/se.tii3-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libcurl.so"
E/AndroidRuntime( 3531): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime( 3531): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 3531): 	at org.artoolkit.ar.base.NativeInterface.loadNativeLibrary(NativeInterface.java:74)
E/AndroidRuntime( 3531): 	at org.artoolkit.ar.unity.CameraSurface.<clinit>(CameraSurface.java:70)
E/AndroidRuntime( 3531): 	at org.artoolkit.ar.unity.UnityARPlayerActivity.onResume(UnityARPlayerActivity.java:153)
E/AndroidRuntime( 3531): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
E/AndroidRuntime( 3531): 	at android.app.Activity.performResume(Activity.java:6076)
E/AndroidRuntime( 3531): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
E/AndroidRuntime( 3531): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
E/AndroidRuntime( 3531): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
E/AndroidRuntime( 3531): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 3531): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 3531): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3531): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3531): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 3531): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3531): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3531): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 3531): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

This issue did not occur for me in 5.2.x

**Comment by MaxMalliaParfitt** [comment]
This was answered to my question: https://github.com/artoolkit/arunity5/issues/32
Temporary fix working well on all androids i have access to

**Comment by Jickelsen** [comment]
Thanks, I'm surprised I didn't see that issue. Closing this issue as duplicate.

**Comment by wallywyyoung** [comment]
Thanks guys!
